### ISSUE TITLE
List all previously used identifiers on IATI Registry

### ISSUE THREAD

**Issue by notshi** [aidtransparency/iati-data#2]
Also raised here - https://github.com/devinit/D-Portal/issues/503

This will enable future proofing of URLs so that old urls can redirect to current data.

**Comment by andylolz** [comment]
+1 this would be great, but it’s not an issue with published IATI data. The idea of this repo (which admittedly I have not explained anywhere yet!) was to be a public record of issues with publishers’ data.

In the case of this ticket, this is presumably something that the secretariat would need to provide. At any rate, there’s currently no means for a publisher to do this (except using the `other-identifier` element where appropriate).
