### ISSUE TITLE
Consider sanity limitations for all strings

### ISSUE THREAD

**Issue by notshi** [aidtransparency/iati-data#3]
For example, according to the [standard](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/transaction/):

> **transaction@ref**
An internal reference linking this transaction back to the publisher’s financial management system. This value must be of type xsd:string.

However, there are no character limitations which means the following is valid data.
![Screenshot-20190409002853-1899x847](https://user-images.githubusercontent.com/1515961/55763610-946bda80-5a5f-11e9-823a-38962e5ce79e.png)
*Source: [Aidstream](https://aidstream.org/files/xml/wep-activities.xml)*

And these are valid ```iati-identifier```.
![Screenshot-20190409004156-680x572](https://user-images.githubusercontent.com/1515961/55763841-b2860a80-5a60-11e9-96ad-90c82c9ec326.png)
*Source: [Registry](https://iatiregistry.org/dataset/wep-activities)*

We found this because Postgres complains about text that is more than 8kb when creating indexes.

**Comment by andylolz** [comment]
This sounds like a proposed schema change. As such, it would be good to raise it on IATI Discuss, probably in "Modifications, Additions, Improvements":
https://discuss.iatistandard.org/c/standard-management/modifications-additions-improvements
